name: CI

on: push

jobs:
    test:
        name: Test

        runs-on: ubuntu-18.04

        strategy:
            matrix:
                php-version: ['7.2', '7.4']
            fail-fast: false

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: xdebug
                    tools: cs2pr, prestissimo
                    extensions: bcmath, intl
            -   name: Cache Dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache
                    key: php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        php${{ matrix.php-version }}-composer-
            -   name: Install Dependencies
                run: composer install --no-ansi --no-interaction --no-progress --no-suggest

#            -   name: Codestyle
#                run: php vendor/bin/phpcs -q --report=checkstyle | cs2pr
            -   name: PHPUnit Problem Matchers
                run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
            -   name: Unit Tests
                run: vendor/bin/phpunit --coverage-text
            -   name: Run Psalm
                run: vendor/bin/psalm --output-format=github
