name: CI

on:
    push:
        branches-ignore:
            - 'master'
        tags-ignore:
            - '**'

jobs:
    test:
        name: Test

        runs-on: ubuntu-latest

        steps:
            # Setup
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.0'
                    ini-values: assert.exception=1, zend.assertions=1
                    coverage: pcov
                    tools: cs2pr
                    extensions: bcmath, intl
            -   name: Cache Dependencies
                uses: actions/cache@v2
                with:
                    path: ~/.composer/cache
                    key: php8.0-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        php8.0-composer-
            -   name: Install Dependencies
                run: composer install --no-interaction --no-ansi --no-progress --no-suggest

            # Test
            -   name: Codestyle
                run: php vendor/bin/phpcs --parallel=`nproc --all` -q --report=checkstyle | cs2pr
            -   name: Psalm
                run: php vendor/bin/psalm --threads=`nproc --all` --output-format=github
            -   name: PHPUnit Checks Matcher
                run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
            -   name: Unit Tests
                run: |
                    php vendor/bin/phpunit --coverage-text=coverage.txt --colors=never
                    COVERAGE=$(php -r 'preg_match("#Lines:\s*(\d+.\d+)%#", file_get_contents("coverage.txt"), $out); echo $out[1];')
                    echo "COVERAGE=${COVERAGE}" >> $GITHUB_ENV
            -   name: Mutation Tests
                run: |
                    php vendor/bin/roave-infection-static-analysis-plugin --only-covered --show-mutations --threads=`nproc --all` --min-msi=100 --min-covered-msi=100 --no-progress > msi.txt
                    cat msi.txt
                    MSI=$(php -r 'preg_match("#\(MSI\):\s*([0-9.]+)%#", file_get_contents("msi.txt"), $out); echo $out[1];')
                    echo "MSI=${MSI}" >> $GITHUB_ENV

            # Report
            -   name: Report PR Status
                uses: actions/github-script@v3.1
                with:
                    github-token: ${{github.token}}
                    script: |
                        const msi = parseFloat(process.env.MSI);
                        const coverage = parseFloat(process.env.COVERAGE);

                        github.repos.createCommitStatus({...context.repo, sha: context.sha, state: msi > 95 ? 'success' : 'failure', context: 'Mutation Score Index', description: msi+'%'});
                        github.repos.createCommitStatus({...context.repo, sha: context.sha, state: coverage > 99 ? 'success' : 'failure', context: 'Unit Test Coverage', description: coverage+'%'});
